# -----------------------------------------------------------------
# GLOBAL PARAMETERS
# See https://github.com/chipzoller/hugo-clarity#global-parameters
# -----------------------------------------------------------------

# Author string replaced by author map (see section further below)
# author = "Nitya Narasimhan"
introDescription = "PhD, Parent, Visual Storyteller, Technology & Community Advocate. Try-Fail-Learn!"

# set the url for the 'read more' button below the introDescription
# if not specified, goes to "about/" page
# set to false to not show the button 
introURL = "about/"

# set to largeTwitterCard to true to show a large twitter card image. 
# The default is a small twitter card image
twitter = "@nitya"
largeTwitterCard = false 

# set your site's description here. 
# will be use for home page content meta tags (seo). 
# Alternatively set this description in your homepage content file i.e content/_index.md. 
# Whatever is set in the latter will take precedence
description = "Welcome to Nitya Narasimhan's home on the multiverse. I'm a PhD, developer advocate and visual storytelling interested in mobile, web, cloud and AI." 

# Show/hide share buttons on each post. Also available in each post's front matter.
showShare = true

# Analytics IDs
ga_analytics = "UA-145095098-1"     #google
# baidu_analytics = "XXXXXXXX"    #baidu

# limit the number of taxonomies links shown on the sidebar of each page by default.
# Applies for all other default & custom taxonomies. 
# e.g categories, brands see https://gohugo.io/content-management/taxonomies#what-is-a-taxonomy
numberOfTagsShown = 5

# will be used on share >> twitter, facebook, linkedin
fallBackOgImage = "images/thumbnail.png"

# sets the maximum number of lines per codeblock. 
# The codeblock will however be scrollable and expandable.
codeMaxLines = 7

# disable showing line numbers by default. 
# Switch to `true` if you'd rather have them on.
codeLineNumbers = false

# enable math notation. Switch to `true` to enable mathjax in your site.
enableMathNotation = false

# directory(s) where your articles are located
# see config details here https://gohugo.io/functions/where/#mainsections
mainSections = ["post"] 

# center logo on navbar
# Set to "true" for centering or "false" for left aligned.
centerLogo = false
logo = "logos/logo.png"

# Label Non inline images on an article body
# toggle on or off globally
figurePositionShow = false 

# you can toggle this behaviour on or off on per page 
# using the same variable inside your articles frontmatter
# the text before image number e.g Figure 1.0
figurePositionLabel = "Figure" 

# Set the collapsed mobile navigation to either appear 
# from the left or the right
mobileNavigation = "right" 

# some site owners want to decide how they would like their sites 
# to be introduced users. These settings give you as a site owner 
# to decide how the user will view your site for the first time.

# please note that you cannot enforce both modes at the same time. 
# i.e by enforcing one mode, you priotise it over the other (by setting it to true). 
# enforceDarkMode will be commented out
# please also not that mode toggle UI will remain in place. 
# That way, if a user prefers darkmode, they can have their way.
enforceLightMode = false
# enforceDarkMode = false

# customize footer icon. 
# see issue https://github.com/chipzoller/hugo-clarity/issues/77
# footerLogo = "icons/copy.svg"

# Text for the languages menu.
# Uncomment this to have drop down menu of supported languages
# Since I have only one (English) I will leave this commented 
# languageMenuName = "ðŸŒ"

# Title separator, default to |.
# titleSeparator = " |"

# Enable or disable comments globally. Default to true.
# comments = false

# Maximum number of recent posts.
numberOfRecentPosts = 3

# Maximum number of featured posts.
numberOfFeaturedPosts = 3

# Date format. Checkout https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for details.
# dateFormat = "2006-01-02" # Default to "Jan 2, 2006".

# toggle to true if you want to use custom fonts only.
# customFonts = false 

# The year when ths website was created, 
# this value is used in the copyright notice of the footer.
since = 2020 

# tell hugo where you store your icons e.g favicons. 
# This is useful if you're using an apache server and there are conflicts 
# >> see issue https://github.com/chipzoller/hugo-clarity/issues/74. If this is applicable to you, be sure to copy the contents of https://github.com/chipzoller/hugo-clarity/tree/master/static/icons to your preferred icons directory 
iconsDir = "icons/" # without a leading forward slash

# website author
[author]
name = "@Nitya N"
photo = "images/nitya200.png" #include this if you would like to show the author photo on the sidebar



[plausible_analytics]

# to enable plausible analytics set to true.
enable = false 

# domain name of your website, most cases same as your base url
websiteDomain = "nitya.dev" 

# default is set to plausible.io, only required if plausible is selfhosted
# plausibleDomain = "plausible.io" 

# default is set to plausible, only required if using a custome name for script
# scritpName = "plausible"

